name: Web Release

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    name: Create Web Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./emotion_wheel/
    steps:
      - uses: actions/checkout@v3
      # Don't need dart-lang since Flutter bundles dart
      #      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          # just use latest rather than specifying a version to try and avoid local dart version mismatch
          #          flutter-version: "3.0.0"
          channel: 'stable'
          cache: true
      - run: flutter --version

      - name: Check Working Directory Contains root pubspec.yaml
        run: |
          pwd
          find . -type f -name pubspec.yaml
      - name: Get dependencies
        # If this step fails because the project root was not in the working dir, check the output of the
        # "Check Working Directory Contains root pubspec.yaml" step to help troubleshoot
        run: flutter pub get

      - name: Clear out any old build files
        run: flutter clean

      - name: Start Web Release Build
        # --base-href is needed so that flutter knows how to adjust resource paths (see web/index.html)
        # The base href needs to match the name of the repository
        # since the page will be hosted at username.github.io/base-href/
        # Note this is not necessarily the same as the project name so double check my_project vs my-project
        run: flutter build web --release --base-href /emotion-wheel/

      - name: Check Working Directory Contains build/web
        run: |
          pwd
          find . -type d -name web

      - name: Upload Web Build Files
        uses: actions/upload-artifact@v2
        with:
          name: web-release
          # This path is from the Working Directory to the build/web dir and may contain the module name
          # if it is in a sub directory and not the root of the repo.  Check the output of the
          # "Check Working Directory Contains build/web" step to help troubleshoot
          path: ./emotion_wheel/build/web

  deploy:
    name: Deploy Web Build
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Web Release
        uses: actions/download-artifact@v2
        with:
          name: web-release

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          force_orphan: true
